AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fiap-lambda51burguer

  Sample SAM Template for fiap-lambda51burguer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  Lambda51Burguer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda51Burguer
      Handler: fiap.App::handleRequest
      Runtime: java21
      Architectures:
      - x86_64
      MemorySize: 512
      Role: arn:aws:iam::862807292265:role/LabRole
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get