# sam/template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fiap-lambda51burguer

Parameters:
  UserPoolId:
    Type: String
    Description: "ID do User Pool do Cognito"
  UserPoolClientId:
    Type: String
    Description: "ID do User Pool Client do Cognito"
  IdentityPoolId:
    Type: String
    Description: "ID do Identity Pool do Cognito"

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON

Resources:
  AuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda51Burguer
      Handler: fiap.App::handleRequest
      Runtime: java21
      MemorySize: 512
      Role: arn:aws:iam::862807292265:role/LabRole
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPoolId
          USER_POOL_CLIENT_ID: !Ref UserPoolClientId
          IDENTITY_POOL_ID: !Ref IdentityPoolId
      Events:
        UserApi:
          Type: Api
          Properties:
            Path: /user
            Method: post
        AdminApi:
          Type: Api
          Properties:
            Path: /admin
            Method: post

Outputs:
  LambdaFunctionArn:
    Description: "ARN da função Lambda"
    Value: !GetAtt AuthLambda.Arn
    Export:
      Name: LambdaFunctionArn
