name: Deploy Lambda Function Validate CPF

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install AWS SAM CLI
        run: pip3 install aws-sam-cli

      - name: Build SAM Application
        run: sam build

      - name: Validate SAM Template
        run: sam validate

      - name: Deploy SAM Application
        run: |
          sam deploy \
            --stack-name sam-teste \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }}
